
# #END GAME
# print("    _____")
# print("    |   |")
# print("    o   |")
# print("   /|\  |")
# print("    /\  |")
# print("        |")
# print("  -------------")

# # step 9
# print("    _____")
# print("    |   |")
# print("    o   |")
# print("   /|\  |")
# print("    /   |")
# print("        |")
# print("  -------------")
# # step 8
# print("    _____")
# print("    |   |")
# print("    o   |")
# print("   /|\  |")
# print("        |")
# print("        |")
# print("  -------------")
# # step 7
# print("    _____")
# print("    |   |")
# print("    o   |")
# print("   /|   |")
# print("        |")
# print("        |")
# print("  -------------")
# # step 6
# print("    _____")
# print("    |   |")
# print("    o   |")
# print("    |   |")
# print("        |")
# print("        |")
# print("  -------------")
# # step 5
# print("    _____")
# print("    |   |")
# print("    o   |")
# print("        |")
# print("        |")
# print("        |")
# print("  -------------")
# # step 4
# print("    _____")
# print("        |")
# print("        |")
# print("        |")
# print("        |")
# print("        |")
# print("  -------------")
# # step 3
# print("         ")
# print("        |")
# print("        |")
# print("        |")
# print("        |")
# print("        |")
# print("  -------------")
# # step 2
print("         ")
print("         ")
print("         ")
print("         ")
print("         ")
print("         ")
print("  -------------")
# # set 1